services:
  rtl-camera-fe:
    build: .
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: development
      API_URL: http://localhost:8080/api/v1/rtl-services
      CHOKIDAR_USEPOLLING: true
    volumes:
      - .:/app